apiVersion: batch/v1
kind: Job
metadata:
  name: stress-test
spec:
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress-test-A
        #image:  lostcauze7/debian-stress:latest
        image:  lostcauze7/ubuntu-stress:latest
        resources:
          limits:
            cpu: "4"
            memory: 32G
          requests:
            cpu: "2"
            memory: 16G
        securityContext:
          runAsUser: 0
          privileged: true
        command:
          - "stress"
        args:
          # Check the docs: https://linux.die.net/man/1/stress
          - "--cpu"
          - "1"
          - "--io"
          - "4"
          - "--vm"
          - "2"
          - "--vm-bytes"
          - "512M"
          - "--timeout"
          - "600"
      restartPolicy: Never